### ISSUE TITLE
ReduceMassAccretionRate cannot use `MeshData` pointer on device

### ISSUE THREAD

**Issue by Yurlungur** [lanl/phoebus#208]
@mari2895 and I discovered a bug in the mass accretionr ate code. It looks like the `MeshData<Real>` pointer `md`. We can't do this as the `MeshData` pointer is a host memory object and the loop is in device memory space. This will crash or cause other issues.

**Comment by AstroBarker** [comment]
Thanks for catching this. Working on it in #209

**Comment by Yurlungur** [comment]
Caused by confusion between branches.
